[WIP] Countersigning
holochain/docs-pages pull request #313
Opened 2021-12-21 00:45 UTC by pdaoust

For everyone's consideration. Notes/questions to reviewers:

* No images yet. Could probably be useful when describing the session.
* Yes, I do pull out that boogeyman, "double spending", only so I can disabuse devs of the idea that countersigning has anything to do with it. Let me know your thoughts on it.
* Does the story describing the sequence of events involved in a countersigning session actually work? does it flow? is it clear?
* Biggest question: is it actually accurate?
* What's being left out? Does it actually explain what countersigning is for?

2021-12-21 00:59 UTC, Connoropolous commented
hey Paul,

nice, glad this is coming together. I actually haven't done deep dive on countersigning nor used it for anything yet, so I will actually be more learning while reading than anything. 

For everyone, here's a direct link to the published draft of Paul's article: https://deploy-preview-313--fervent-tesla-2a3da2.netlify.app/concepts/10_countersigning

2021-12-21 01:00 UTC, Connoropolous commented
@pdaoust It says "The eventual hash of the entry that will be countersigned" and I'm thinking you meant to put that word "eventual" at the end of the sentence?

2021-12-21 15:34 UTC, jost-s commented on src/concepts/10_countersigning.md
> +* Once a party receives all counterparties, headers, they commit the new element to their own source chain and publish it.
the comma should be an apostrophe "all counterparties' headers"

2021-12-21 15:34 UTC, jost-s commented on src/concepts/10_countersigning.md
> +* Once the DHT peers have collected the full list of headers, they broadcast them to all parties.
I don't understand this together with the next takeaway.

1. The entry's headers are being published
2. The DHT peers (other than the parties I suppose?) receive the full list of headers and broadcast them (didn't the parties receive them as well?).
3. Once a party receives all headers of all counterparties, they commit the element

2021-12-21 23:34 UTC, pdaoust commented on src/concepts/10_countersigning.md
> +2. Alice sends the preflight request to Bob for approval. (You can implement this any way you like, but a [remote call](../8_calls_capabilities/) is probably the most reliable.)
The data structures and the session negotiation stuff are all provided by Holochain; the means of transporting the preflight is the part you have to build yourself. Should I make that clearer somehow?

2021-12-21 23:38 UTC, pdaoust commented on src/concepts/10_countersigning.md
> +* Once the DHT peers have collected the full list of headers, they broadcast them to all parties.
Yeah, I'm struggling with how to articulate this too. It goes like

1. Parties prepublish their headers to entry hash's neighbourhood
2. Parties wait for neighbourhood to collect everyone's headers and broadcast them to everyone
3. Either:
    * Session times out (parties unlock their chain and throw away the not-yet-committed entry, along with other entries committed in same function call, neighbourhood forgets prepublished headers)
    * Session succeeds (parties write the entries and publish all ops 'for real' this time -- header, entry, and agent activity)

Sounds like better clarity is in order.

2021-12-21 23:39 UTC, pdaoust commented on src/concepts/10_countersigning.md
> +10. Once those authorities have collected all headers, they send the full header set to both Alice and Bob. (If Alice and Bob reach the end of the time window without receiving this header set, howev
Sure, I can write about that. Basically, there is no retry unless you implement it yourself.

2021-12-21 23:40 UTC, pdaoust commented
@Connoropolous I can certainly move the 'eventual' thing around :+1:

2021-12-22 00:07 UTC, pdaoust commented
@jost-s check out the most recent commit; I've tried to tackle your feedback. Hope I'm not getting too wordy 🤞🏼

2021-12-22 02:24 UTC, artbrock requested changes

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +Here's a more in-depth look at this process. Keep in mind that it's meant to be an automated process, finished within a few seconds while Alice and Bob are both online. Any human agreement (such as n
**Suggest:** ...should happen beforehand, and already be saved to the respective chains as a pre-authorization for this countersigning action.

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +    * The parties involved (her and Bob)
**Change:** her --> Alice

The grammar as to whether to use the subjective (she) or objective form (her) is ambiguous here (and therefore an unnecessary distraction) She and Bob are the parties involved. The parties are her and Bob. "Alice" works clearly in both cases.

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +    * Optional application data
**Suggest**: Optional application data (such as reference to a pre-authorization record showing the human negotiation is complete).

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +2. Alice sends the preflight request to Bob for approval. (You can implement this any way you like, but a [remote call](../8_calls_capabilities/) is probably the most reliable.) At this stage, Bob co
alice --> Alice

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +9. Once validation is finished, Alice and Bob both 'pre-publish' the new element, with their own header, to the DHT --- but only to the entry authorities. This shows their intention to fully commit t
Suggest: ...go to the same set of DHT authorities.

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +10. Once those authorities have collected all headers, they send the full header set to both Alice and Bob. (If Alice and Bob reach the end of the time window without receiving this header set, howev
Suggest: Once any of those authorities have collected all headers, they send the full header set to both Alice and Bob. (However, if Alice and Bob reach the end of the time window without receiving this header set, their conductors discard the new element and unlock their source chains as if nothing had happened. Likewise, the authorities discard the pre-published data if they don't receive the required signatures in the time window. There is no built-in feature to retry an expired session, but it could be built into the application.)

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +You could see a blockchain as simply **a mechanism for determining what doesn't exist**, by making a decision about what _does_ exist and rejecting all other possibilities. Many transactional applica
transfer-of-title (missing second dash)

2021-12-22 02:24 UTC, artbrock commented on src/concepts/10_countersigning.md
> +But, as we've mentioned, that's not the job of countersigning. Countersigning merely seals the deal once the parties are ready.
Suggest: But since you can already detect double-spend attempts in someone's source chain, that is not the job of countersigning. Countersigning simply allows a group of people to make an identical change to all their chains as a unified operation -- all chains change, or no chains change.

2021-12-22 02:24 UTC, artbrock commented on src/concepts/11_migration.md
>      This page describes an unimplemented feature. In the meantime, you can implement it yourself by defining your own open and close chain entry types (if needed) and writing migration routines that
Suggest: This page includes an unimplemented feature.

2021-12-23 13:00 UTC, jost-s commented on src/concepts/10_countersigning.md
> +* Once the DHT peers have collected the full list of headers, they broadcast them to all parties.
Reading through the page again I find that the detailed steps are clear, and that this part of the takeaways reiterates what has been said before. We could therefore keep takeaways 1, 2 and 3 as well as the last 3 and summarize the ones in-between.

E. g. 
* preflight requests to all parties ensure that a countersigned entry can be written at the given time window
* preflight responses make up the countersigning session data
* all parties validate the entry against the countersigning session data before attempting to commit it
* the entry is first published to the DHT, validated by authorities and then committed to each party's source chain

2023-02-08 04:40 UTC, pdaoust commented
Closing in favour of #357 , which incorporates most of the suggestions, adds new content, and also works with Matthew's new 11ty site structure.

2023-02-08 04:40 UTC, closed without merging