quick setup: introduce setup script
holochain/docs-pages pull request #372
Opened 2023-02-22 15:28 UTC by jost-s

This PR replaces the installation instructions for Nix package manager and cachix setup with a setup script. An additional step in the script is now that Nix flakes and `nix` commands are enabled for the current user.

2023-02-22 18:59 UTC, pdaoust requested changes
Looks great, and I'm so excited to see this happening. Only one stylistic change and one question about the removal of 'Install'.

2023-02-22 18:59 UTC, pdaoust commented on src/pages/quick-start/index.md
> +## Holochain on Linux, macOS and Windows
I'm curious about the reason for removing the word 'Install' here?

2023-02-22 18:59 UTC, pdaoust commented on src/pages/quick-start/index.md
> +### Install the Nix Package Manager & set up Holochain binary cache
```suggestion
### Install the Nix Package Manager and set up Holochain binary cache
```

2023-02-22 18:59 UTC, pdaoust commented on src/pages/quick-start/index.md
> +nix run github:holochain/holochain#hc-scaffold -- example forum
This change is interesting, because it quietly delivers on something Art's been wanting for a while -- removing holochain.love. Seems like a good change to me 👍🏼

2023-02-22 19:28 UTC, steveeJ requested changes
nice! almost there :blush:

2023-02-22 19:28 UTC, steveeJ commented on src/pages/quick-start/index.md
> +bash <(curl https://holochain.github.io/holochain/setup.sh)
does it really need to be bash? i don't think we're using exclusive bash features in the script.

```suggestion
sh <(curl https://holochain.github.io/holochain/setup.sh)
```

2023-02-22 19:28 UTC, steveeJ commented on src/pages/get-building/index.md
> +nix run github:/holochain/holochain#hc-scaffold -- web-app"
```suggestion
nix run github:/holochain/holochain#hc-scaffold -- web-app
```

2023-02-22 19:28 UTC, steveeJ commented on src/pages/quick-start/index.md
> +The Nix package manager, which we use to install and manage Holochain development tools, only supports Mac and Linux. Linux can be run under Windows with [WSL2 (Windows Subsystem for Linux)](https://
why did you remove the "works natively"? i personally think that's a relevant information for windows users.

2023-02-23 02:09 UTC, jost-s commented on src/pages/quick-start/index.md
> +bash <(curl https://holochain.github.io/holochain/setup.sh)
`sh` didn't work and I didn't want to spend more time on figuring it out. If you know how to make it work, welcome!

2023-02-23 02:15 UTC, jost-s commented on src/pages/quick-start/index.md
> +## Holochain on Linux, macOS and Windows
I've found calling this "Installation" funny from the beginning. It's installing a package manager and then setting up a cache to get pre-compiled packages from. It's not "installing Holochain". After running these commands Holochain isn't installed, you can't run a Holochain command. It's unlike installing "Vue" or "npm".

It would be "Installing development environment tools for Holochain on Linux, macOS and Windows" I'd say, but that's a bit long for my taste.

2023-02-23 02:31 UTC, jost-s commented on src/pages/quick-start/index.md
> +The Nix package manager, which we use to install and manage Holochain development tools, only supports Mac and Linux. Linux can be run under Windows with [WSL2 (Windows Subsystem for Linux)](https://
I find it doesn't add anything substantial and instead leaves room for interpretation. If I say "it's supported under Windows" or "it runs under Windows", it's implicit that it's a native binary for Windows.
When I say "it works under Windows, but not natively, you need to run it in a VM or an emulator or so" - well that's true for everything that's not supported under a certain OS. It's like saying "Visual Studio works under macOS, just not natively, you need to run it in a VM with Windows".

2023-02-23 08:31 UTC, steveeJ commented on src/pages/quick-start/index.md
> +bash <(curl https://holochain.github.io/holochain/setup.sh)
do you mean that the nix installation didn't for you either? that'd be very surprising for me because this is the way it's documented on nixos.org

2023-02-23 13:04 UTC, jost-s commented on src/pages/quick-start/index.md
> +bash <(curl https://holochain.github.io/holochain/setup.sh)
It does work when run as a command. It doesn't work inside of this script.

2023-02-28 07:18 UTC, steveeJ commented on src/pages/quick-start/index.md
> +bash <(curl https://holochain.github.io/holochain/setup.sh)
i'll let this one be a mystery as of now especially since we rely on bash inside the script now too

2023-02-28 08:15 UTC, steveeJ approved these changes
there now is a CI job testing this script on ubuntu and macos, and here's [a successful run](https://github.com/holochain/holochain/actions/runs/4290444975/jobs/7474468010) with [the most recent changes](https://github.com/holochain/holochain/pull/2017).

i tested it manually in a fresh ubuntu distribution of WSL2 and confirm it works :+1:

![image](https://user-images.githubusercontent.com/1181362/221793416-5191ba38-6f1b-4e62-9cf7-7b3914b58e03.png)

2023-03-06 14:39 UTC, zippy requested changes
I've offered a few small changes.  I do think we should move forward with this as it's a great improvement.

2023-03-06 14:39 UTC, zippy commented on src/pages/quick-start/index.md
> +## Holochain on Linux, macOS and Windows
```suggestion
## Install the Holochain Dev Environment
```

2023-03-06 14:39 UTC, zippy commented on src/pages/quick-start/index.md
> +### Scaffold Your First Holochain App
```suggestion
### Scaffold An Example Holochain App
```

2023-03-06 14:39 UTC, zippy commented on src/pages/quick-start/index.md
> +### Scaffold Your First Holochain App
This section was confusing in that it actually sounded like you were going to scaffold your OWN first holochain app, but the the script scaffolds OUR example hApp.  I think we need to re-think how we do this, but for now changing the title as above makes it a little clearer.

2023-03-06 18:28 UTC, jost-s commented on src/pages/quick-start/index.md
> +The Nix package manager, which we use to install and manage Holochain development tools, only supports Mac and Linux. Linux can be run under Windows with [WSL2 (Windows Subsystem for Linux)](https://
```suggestion
The Nix package manager, which we use to install and manage Holochain development tools, only supports Mac and Linux. Please install Linux under Windows with [WSL2 (Windows Subsystem for Linux)](https://learn.microsoft.com/en-us/windows/wsl/install){target=_blank}.
```

2023-03-08 00:30 UTC, merged