update index.md
holochain/docs-pages pull request #377
Opened 2023-02-25 08:18 UTC by matthewjosef

wording and markdown fixes.

2023-03-02 23:31 UTC, marycamacho commented on src/pages/get-building/index.md
> +| :exclamation:  note Pre-requisite: Holochain installed as per [Quick Start](../quick-start/index) |
This change should be be reverted as the other code is using current markdown per the new spec.

2023-03-02 23:35 UTC, marycamacho commented on src/pages/get-building/index.md
> +```
are you using the ``` full line of code snippet  instead of the `code words` inline form here on purpose?

2023-03-02 23:37 UTC, marycamacho requested changes
The first change should be reverted but I think the others will work fine. I did not do a cross browser test on this but will do so before we merge. Otherwise it's just my one other question about your intention on code snippets.

2023-03-06 19:21 UTC, pdaoust commented on src/pages/get-building/index.md
> +```bash
```suggestion

```bash
```

2023-03-06 19:22 UTC, pdaoust commented on src/pages/get-building/index.md
> +Type in a name for the zome.  In this case we can just use the same name as the DNA
```suggestion
Type in a name for the zome.  In this case we can just use the same name as the DNA:

```

2023-03-06 19:22 UTC, pdaoust commented on src/pages/get-building/index.md
> +You should then see:
```suggestion
You should then see:

```

2023-03-06 19:22 UTC, pdaoust commented on src/pages/get-building/index.md
> +You will then see
```suggestion
You will then see:

```

2023-03-06 19:23 UTC, pdaoust commented on src/pages/get-building/index.md
> +```
```suggestion
```

```

2023-03-06 19:24 UTC, pdaoust commented on src/pages/get-building/index.md
> +```
ack, GitHub is getting confused. What I'm trying to do is add a newline after the `\`\`\``, not delete it entirely.

2023-03-06 19:25 UTC, pdaoust commented on src/pages/get-building/index.md
> +```text
```suggestion

```text
```

2023-03-06 19:25 UTC, pdaoust commented on src/pages/get-building/index.md
> +type:
```suggestion
Type:

```

2023-03-06 19:26 UTC, pdaoust commented on src/pages/get-building/index.md
> +type
```suggestion
Type:

```

2023-03-06 19:26 UTC, pdaoust commented on src/pages/get-building/index.md
> +The scaffolding tool can add zome and UI functions for updating and deleting entries.  In the case of our todo app we want to be able to do both, which is the default, so just press `<enter>`
```suggestion
The scaffolding tool can add zome and UI functions for updating and deleting entries.  In the case of our todo app we want to be able to do both, which is the default, so just press `<enter>`.
```

2023-03-06 19:26 UTC, pdaoust commented on src/pages/get-building/index.md
> +Type:
```suggestion
Type:

```

2023-03-06 19:26 UTC, pdaoust commented on src/pages/get-building/index.md
> +and press `<enter>`
```suggestion

and press `<enter>`.
```

2023-03-06 19:27 UTC, pdaoust commented on src/pages/get-building/index.md
> +2. Replace the "EDIT ME! Add the components of your app here." text (about halfway down the page of the App.svelte file) with:
```suggestion
2. Replace the "EDIT ME! Add the components of your app here." text (about halfway down the page of the App.svelte file) with:

```

2023-03-06 19:27 UTC, pdaoust commented on src/pages/get-building/index.md
> +- Seeing strange language in these steps look up the words in the [Glossary](../references/glossary.md). |
```suggestion
- Seeing strange language in these steps? Look up the words in the [Glossary](../references/glossary.md). |
```

2024-03-22 21:02 UTC, pdaoust commented
This one is obsolete; there's a new guide.

2024-03-22 21:02 UTC, closed without merging