Holo docs for alpha
holochain/docs-pages pull request #405
Opened 2023-10-13 13:14 UTC by alastairong

2023-10-16 11:07 UTC, alastairong commented
@pdaoust Really appreciate your work formatting, aligning styles, and getting the docs compiling! I was wondering about how to do that

2023-10-16 20:57 UTC, pdaoust commented
@alastairong no prob -- the build problem was apparently caused by a plugin called Prism, which highlights code samples at compilation time.

I've gone and done a big editing sweep; I've got some follow-up questions that I'll do as a review.

2023-10-16 22:25 UTC, pdaoust requested changes

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +Since AdminWebsocket functionality is handled via Envoy, a service running on Holo hosts that handles the provisioning of hApps, Holo decides whether to show a "sign-up" or "log-in" form based on whe
I don't quite understand this sentence -- is it saying that things normally accessible in the self-hosted context are not accessible in the Holo context because Envoy intercepts some of them? If that's the case, this is (or should be) true of the self-hosted context too -- admin websocket shouldn't be accessible to the UI. So the sentence on line 748 might also describe a call that UI devs shouldn't be making anyway.

(Check my facts; I might be wrong about this)

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +This generally results in a UI with a much more asynchronous programming pattern, whereas native Holochain UIs tend to be use a more synchronous programming pattern.
So far I've mostly seen native HC UIs programming in async style because it's all about waiting for WebSocket responses. Is there more beyond this that needs to be done -- some sort of mounting/unmounting of all zome calls based on agent state?

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +By default, Holo will run read-only cells of deployed applications **under each host's agent** in addition to any user cells. These cells serve two purposes:
```suggestion
By default, Holo will run **read-only cells** of deployed applications **under each host's agent** in addition to any user cells. These cells serve two purposes:
```

Thought that point deserves extra emphasis.

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +This behavior is available by default. Once a WebSDK client has been instantiated and before a user derives their agent keys, any zome calls will follow this pattern and have read access by default.
How does this work -- how does the stack know which functions are only going to need read access? What cap grant does an anonymous Chaperone connection use? AFAIU this would require an unrestricted grant on all zome functions.

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +If you want to securely disable this functionality, you will need to implement a membrane proof with read-only restrictions. As a less secure alternative, you can:
* Which functionality specifically? the 'free pass to everything' functionality?
* I'm confused by the phrase 'implement a membrane proof with read-only restrictions' -- do you mean a membrane proof validation function that allows the read-only agent's membrane proof paired with a general validation function that denies any source chain writes? Or are source chain writes denied at the conductor level somehow?
* I'm not sure we need to give a less secure alternative -- I'd prefer just giving one (secure) piece of advice to everyone. Thoughts?

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +Due to the security implications of multi-tenant conductors, `AdminWebsocket` (and some `AppWebsocket`) functionality is not directly exposed to Holo clients. Instead, this functionality is exposed v
```suggestion
Due to the security implications of multi-tenant conductors, `AdminWebsocket` (and some `AppWebsocket`) functionality is not directly exposed to Holo clients. Instead, this functionality is exposed indirectly via Holo WebSDK methods where appropriate.
```

Am I right about that?

But also, as mentioned above, this also should be true of native HC UIs. The fact that it isn't yet is just because the restriction isn't enforced yet.

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +Holo strongly recommends membrane proof implementations for production or long-running applications. However, as noted earlier, Holo installs and runs cells of deployed applications under each host’s
```suggestion
Holo strongly recommends membrane proof implementations for production or long-running applications. However, as noted earlier, Holo installs and runs read-only cells of deployed applications under each host’s agent to provide high-uptime DHT nodes and to serve data to anonymous users and Web2 participants who do not have keys. **These cells always have a zero-byte membrane proof.**
```

I've got this right, right? This feels like the important take-home message; if you want to create a restricted membership but still allow the read-only instances to serve public content and maintain DHT resilience, you've got to look for the read-only membrane proof.

(I have separate concerns about the easy forgeability of a zero-byte membrane proof that would allow a non-host access to any DHT they wanted, if the following were implemented in a DNA -- am I wrong about how that works?)

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +Membrane proofs that restrict this read-only access prevent Holo from providing such affordances for your hApp. This may be an acceptable trade-off or desired behaviour. However, If you want to benef
```suggestion
DNAs that require membrane proofs restrict this read-only access and thus prevent Holo from providing such affordances for your hApp. This may be an acceptable trade-off or desired behaviour. However, If you want to benefit from always-on nodes and read-only access while having a membrane proof, you will need to configure your membrane proof logic to allow "unpermissioned" read-only access like below:
```

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +pub fn validate_joining_code(
This function might be misconstrued as an official callback. I wonder if we could demonstrate the use of this function within `validate()`?

It also seems like it needs validation code to deny all source chain writes past the genesis records -- or is this enforced at the conductor level?

2023-10-16 22:25 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```rust
As mentioned above, I'd recommend moving this restriction to the integrity zome's `validate()` function, so that any records past `InitComplete` are prevented at both the conductor and DHT level and can't be circumvented by simply hot-swapping coordinator zomes. I don't know what this would look like -- how many different types of `Op` you'd have to put this guard on. Probably all of them 🤷🏼‍♂️ The one problem with this is that you'd have to do it for _each_ integrity zome, and some of those zomes might be third-party.

2023-10-17 08:01 UTC, alastairong commented on src/pages/references/enable-holo.md
> +In both cases there are no required DNA changes for Holo Hosting --- only UI changes. However, Holo operates under a different context and we highly recommend that you read the core concepts, in part
Ah! I meant the Holo Core Concepts which is the section below that you're referring to. I wonder how we structure this better

2023-10-17 08:05 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```typescript
It should be in App.vue. How should we add it in? Do we just spell it out like "Let's look at App.vue"? Or is there a smarter way?

2023-10-17 08:08 UTC, alastairong commented on src/pages/references/enable-holo.md
> +You can then initialize a context-dependent client, assuming you want your UI to be compatible with both Holo and Holochain.
The data() function itself doesn't check right?

2023-10-17 08:11 UTC, alastairong commented on src/pages/references/enable-holo.md
> +  async mounted() {
mounted()? This is a Vue lifecycle function to specify logic that occurs when the UI elements are mounted to the DOM. And yes we add logic in here specific to Holo.

I haven't had all the experience of writing documentation that you have so I'm not sure what we really need to call out about this - seemed self-apparent to me. Can you suggest something?

2023-10-17 08:12 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```
Yes. I didn't think it was important but you're right that it's literally the only thing left out

2023-10-17 08:13 UTC, alastairong commented on src/pages/references/enable-holo.md
> +    }
```suggestion
    }
}
```

2023-10-17 08:14 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```
```suggestion
    }
}
```
```

2023-10-17 08:16 UTC, alastairong commented on src/pages/references/enable-holo.md
> +Unlike in pure Holochain, you cannot assume that a user has provided their desired keys when the connection is established. This may require changes to your application logic. You can read more at ht
Yes they may not have generated their keys yet. When they haven't, we have some throwaway / temporary keys generated for them. To be honest I'm unclear as to why.

2023-10-17 08:21 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```nix
We can't as Holo Network itself is on 0.2.x

I'm happy to keep this as a feature branch until we get to 0.2.x stable

2023-10-17 08:24 UTC, alastairong commented on src/pages/references/enable-holo.md
> +!!! info
Do you mean the chaperoneUrl advice? I'm sure there is. We can add it to the todo list

2023-10-17 08:25 UTC, alastairong commented on src/pages/references/enable-holo.md
> +Holo does not support direct programmatic/API access to deployed hApps.
It's just not productised yet. We actually have a POC implementation of this in our HRL gateway that fractal-tribute uses.

2023-10-17 08:27 UTC, alastairong commented on src/pages/references/enable-holo.md
> +    * (Optional) Configuration of memproof/registration code.
No this is not a deploy guide and the content re: how to properly configure registration code / memproof set up is part of a deploy guide. We might revisit this if there is a learning pathway issue but right now I'd rather we prepare a "deploy guide" as a standalone.

2023-10-17 08:30 UTC, alastairong commented on src/pages/references/enable-holo.md
> +Due to the security implications of multi-tenant conductors, `AdminWebsocket` (and some `AppWebsocket`) functionality is not directly exposed to Holo clients. Instead, this functionality is exposed v
Should it be true of native HC UIs? Or do you mean "exposed to the end user". Because I mean that someone developing a UI for Holohosting using web-sdk cannot make AdminWebsocket calls.

2023-10-17 08:46 UTC, alastairong commented on src/pages/references/enable-holo.md
> +Holo strongly recommends membrane proof implementations for production or long-running applications. However, as noted earlier, Holo installs and runs cells of deployed applications under each host’s
That is correct. I'm wondering if we should clarify that "Holo CAN install..." i.e. you can disable this functionality by simply not providing the zero-byte membrane proof. What do you think?

Re: the easy forgeability, yes that is also something on our radar that we don't have a good answer to currently. Long term the solution is to allow HoloPorts to request membrane proofs from the happ manager's infrastructure directly using some sort of secret.

2023-10-17 08:47 UTC, alastairong commented on src/pages/references/enable-holo.md
> +pub fn validate_joining_code(
@robbiecarlton Can you answer this question?

2023-10-17 08:48 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```rust
@robbiecarlton This one too

2023-10-17 08:51 UTC, alastairong commented on src/pages/references/enable-holo.md
> +    3. Runs a web server to serve the UI.
Yea I guess technically. It's an out-of-the-box thing for most UI frameworks to make the UI available at localhost right?

2023-10-17 08:53 UTC, alastairong commented on src/pages/references/enable-holo.md
> +3. Access your two agents on your browser at `http://localhost:8888` and `http://localhost:8889`.
At launch, they are two separate anonymous instances with throwaway keys. Depending on application logic they might just immediately direct to a login/signup page, or allow read-only use at first.

I don't know exactly how we keep their chaperone instances separate.

2023-10-17 08:54 UTC, alastairong commented on src/pages/references/enable-holo.md
> +Only minor UI changes are technically required for Holo hosting. However, Holo operates under a different set of assumptions and we highly recommend that you read the [Core Concepts](/concepts/). It
Yup - let's agree how we want to structure the Holo "core concepts" and what name we even want to call it, given the confusion with Holochain Core Concepts

2023-10-17 08:55 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```typescript
Yea...structurally it's part of the snippet above actually. I manually split it out but perhaps that's a bad idea that causes confusion. I'll make a separate commit to address this.

2023-10-17 08:56 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```html
It's still part of App.vue in the scaffold I think? Just in the html section.

2023-10-17 08:56 UTC, alastairong commented on src/pages/references/enable-holo.md
> +```typescript
App.vue again. Lower down after the data() section there's a methods section.

2023-10-17 08:56 UTC, alastairong commented on src/pages/references/enable-holo.md
> +During sign-up a registration code field can be shown to enable [**membrane proof**](/glossary/#membrane-proof) workflows. Holo strongly recommends that you implement a membrane proof for production
Thanks. Yes it's good to keep the info aligned across both.

2023-10-17 12:59 UTC, alastairong commented on src/pages/references/enable-holo.md
> +To connect your application to `holo-dev-server`, point the client's `chaperoneUrl` to `https://localhost:24274`.
Ok any action required here? If not please hit resolve :)

2023-10-17 13:47 UTC, alastairong commented on src/pages/references/enable-holo.md
> +Since AdminWebsocket functionality is handled via Envoy, a service running on Holo hosts that handles the provisioning of hApps, Holo decides whether to show a "sign-up" or "log-in" form based on whe
AdminWebsocket calls aren't exposed to the UI?

2023-10-17 14:08 UTC, alastairong commented on src/pages/references/enable-holo.md
> +This generally results in a UI with a much more asynchronous programming pattern, whereas native Holochain UIs tend to be use a more synchronous programming pattern.
So my impression is that in native Holochain you have serial async approach

I.e. 
```
async function foo() -> Promise<Bar> { ... }
const result = await foo

```

In Holo UIs you tend to have more of a listener pattern i.e.

```
async function foo() -> Promise<Void> { ... }

listener.on('event_that_foo_triggers') => { ... }
```

2023-10-17 14:11 UTC, alastairong commented on src/pages/references/enable-holo.md
> +This behavior is available by default. Once a WebSDK client has been instantiated and before a user derives their agent keys, any zome calls will follow this pattern and have read access by default.
Thanks. This is old. I will update in a separate PR

2023-10-17 14:12 UTC, alastairong commented on src/pages/references/enable-holo.md
> +If you want to securely disable this functionality, you will need to implement a membrane proof with read-only restrictions. As a less secure alternative, you can:
Happy to remove the less secure alternative. It's kinda hacky.

2023-10-17 14:15 UTC, alastairong commented on src/pages/references/enable-holo.md
> +If you want to securely disable this functionality, you will need to implement a membrane proof with read-only restrictions. As a less secure alternative, you can:
I think generally I need to re-write this section

2023-10-17 19:47 UTC, robbiecarlton commented on src/pages/references/enable-holo.md
> +```rust
Paul's right, this would be more correct.

2023-10-17 21:02 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +If you want to benefit from always-on nodes and read-only access while having membrane proofs, you will need to implement special "Holo-safe" logic. You can [read more here](https://link.to.core.conc
I'd like to have a Holo core concepts section, sure. Then we could link out to it from all sorts of places.

2023-10-17 21:03 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +    3. Runs a web server to serve the UI.
ohhhhhhhhhhh it's the UI framework itself that has a local dev server? got it.

2023-10-17 21:05 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +  async mounted() {
if the function already exists in the Vue file (say, as a stub) let's just be explicit -- "edit the two Vue lifecycle functions so they read as follows" or something like that.

2023-10-17 21:07 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```typescript
okay, so it sounds like all the edits are to `App.vue` then? Let's put something near the top to say "all edits you'll be making will be to your UI's entry point -- in this case, `App.vue`" and then give a bit of context for each snippet (e.g., "put this stuff in the section that starts with ___")

2023-10-17 21:08 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```nix
aw dang! Good to know. Yes, let's keep this as a feature branch unless we get a pull (from you, Rob, some business decision-maker, whoever) to get that documentation online. We'll want to put a caveat at the top that hApp devs will need to either start scaffolding from some 0.2 channel of Holonix or upgrade their DNAs to 0.2.

2023-10-17 21:15 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +To connect your application to `holo-dev-server`, point the client's `chaperoneUrl` to `https://localhost:24274`.
I have no idea why I've got it as a suggestion that changes nothing 🤔 I'll think of a way to elaborate on what's needed.

2023-10-17 21:30 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +!!! info
yes, the chaperoneUrl advice, along with `VITE_APP_IS_HOLO` env var. So you've got three scenarios:

* `build` w/o any env vars builds the UI for native HC
* `build:holo` passes `VITE_APP_IS_HOLO=true` and a production `VITE_APP_CHAPERONE_URL` env vars (with alternatives for other front-end toolkits, of course)
* for local dev, allow the parent `package.json` to specify those env vars, as in the example you gave.

2023-10-17 21:33 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +This generally results in a UI with a much more asynchronous programming pattern, whereas native Holochain UIs tend to be use a more synchronous programming pattern.
ohh, got it, so you wouldn't use `await` as much in Holo-hosted? Is that because of higher latency / greater risk of disconnection?

2023-10-17 21:59 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```rust
How to make this performant is a question though -- you don't want to be doing a `must_get_agent_activity` on every single zome call. I suppose it could work like this when validating:

1. If the preceding source chain action is an agent key, require a non-read-only membrane proof preceding it.
2. If the preceding source chain action is anything else and a validator has marked it valid, it's assumed it was also subjected to these two rules, so the action currently being valid must also be writable.

This recursive rule inductively validates a whole chain but only requires a single DHT get per validation. (Of course, it also depends on the honesty of validators.)

2023-10-17 22:03 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```
annoyingly, the way GH's suggestion fences work, the closing fence is lost. I ran into this yesterday -- had to edit it locally and push the changes.

2023-10-19 15:28 UTC, alastairong commented on src/pages/references/enable-holo.md
> +    3. Runs a web server to serve the UI.
Ah I see. Yea

2023-10-19 20:11 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```rust
Another problem (mentioned in chat, but noting here for visibility) is that this would have to be explicitly coded into the validation function of each integrity zome, which would prevent you from using third-party zomes. All in all, the validation approach is 'more correct' (= secure) if zero-byte memproofs are to be used, but very challenging to make workable in our current composability model -- Integrity zomes are closed to both modification and extension.

2023-10-19 21:50 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +```
I looked at the actual current state and it looks like you resolved this 👍🏼

2023-10-20 18:02 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +The WebSDK client loads and connects to an iframe called Chaperone. Chaperone is a key and connection manager to the Holo network and is invisible outside a few specific cases. Let's initialise this
```suggestion
The WebSDK client loads and connects to an iframe called Chaperone. Chaperone is a key and connection manager to the Holo network and is invisible outside a few specific cases. Let's initialize this client in the Vue `mounted()` lifecycle hook.
```

I am so sorry; we've standardised on American spelling. It pains me too. (my spell checker tells me 'standardised' is spelled wrong and I'm stubbornly ignoring it. But I would write 'standardized' in the dev docs)

2023-11-07 22:33 UTC, pdaoust approved these changes

2023-11-08 11:37 UTC, alastairong commented on src/pages/references/enable-holo.md
> +To implement logic that allows read-only cells to join a DNA's network but not write data, your integrity zome's validation function should check the author's membrane proof, then allow them to join
```suggestion
In order to provide high-uptime nodes and anonymous hosted user access via read-only cells while keeping your hApp safe from defacement, you'll need to restrict what a read-only cell can do. A read-only cell is **read-only merely by convention**; that is, because you're checking for read-only cells and handling writes differently.

The most secure way to restrict access to a hApp's data is with [**membrane proofs**](/references/glossary/#membrane-proof). A membrane proof is supplied at installation time and acts like an ID card, allowing the hApp to admit valid members only. However, this prevents Holo hosting devices from provisioning read-only cells unless explicit affordances are made.

The Holo Network expects and uses a zero-byte membrane proof for read-only cells. A publicly known membrane proof without restriction is essentially the same as no membrane proof. To implement logic to allow read-only cells to join a DNA's network but not write data, your integrity zome's validation function should check the author's membrane proof, then allow them to join the network but reject CRUD operations if the proof is zero bytes.

(Note that, in the future, the production Holo hosting network may permit you to implement logic that provisions membrane proofs to read-only nodes, allowing you to use Holo for high-uptime while preventing anonymous read access.)
```

2023-11-08 11:37 UTC, alastairong commented on src/pages/references/enable-holo.md
> +The following code shows an example of how to do both of these things. This isn't necessarily the most performant solution, as it requires a validator to retrieve the author's entire source chain (ex
Why can't we do the better-performing one? If people are basically going to copy and paste this stuff we should write something we are happy with. Especially since changing this will be an integrity zome change.

2023-11-09 18:19 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +To implement logic that allows read-only cells to join a DNA's network but not write data, your integrity zome's validation function should check the author's membrane proof, then allow them to join
brilliant, thanks!

2023-11-10 13:22 UTC, zo-el commented on src/pages/references/enable-holo.md
> +    Ok(!is_read_only_membrane_proof(membrane_proof.unwrap()))
The unwrap in this statement can panic because the agent could have no mem-proof, right?

2023-11-10 13:22 UTC, zo-el commented on src/pages/references/enable-holo.md
> +            }
This if statement needs an else

2023-11-10 13:22 UTC, zo-el commented on src/pages/references/enable-holo.md
> +            match op.entry_data().unwrap() {
The unwrap can panic too right? because the initial creates do not have entries just actions

2023-11-10 13:40 UTC, zo-el commented on src/pages/references/enable-holo.md
> +    })?;
This create is going to require write access, and with the above validation rule, it will block the read-only mem-proof from committing this grant right?

2023-11-10 13:45 UTC, zo-el commented on src/pages/references/enable-holo.md
> +        tag: "".into(),
```suggestion
        tag: "read-only".into(),
```

2023-11-14 19:20 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +            }
This is just to get around the awkward fact that I've already checked the action type so I know the op's associated action is `AgentValidationPkg`. All I'm doing here is `if let` matching on a condition I know must be true. I've simplified it in a later commit.

2023-11-14 19:31 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +            match op.entry_data().unwrap() {
Hm, yeah, looks like `Action::entry_data()` is guaranteed to return something meaningful for new-entry actions (even for private entries, and even for ops that don't carry entry bytes), but not for delete-entry actions. Nice catch, thank you.

2023-11-14 19:34 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +        tag: "".into(),
nice idea.

2023-11-14 19:38 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +The following code shows an example of how to do both of these things. This isn't necessarily the most performant solution, as it requires a validator to retrieve the author's entire source chain (ex
done, except for review on the code of the better-performing one.

2023-11-14 21:06 UTC, pdaoust commented on src/pages/references/enable-holo.md
> +    }.unwrap() {
crap, this will regularly panic now, I bet. Just about to push a fix.

2023-11-23 17:10 UTC, zo-el commented on src/pages/references/enable-holo.md
> +        if let EntryType::AgentPubKey | EntryType::CapClaim | EntryType::CapGrant = op.entry_data().unwrap().1 {
I am always sceptical of using unwrap, especially in the integrity zome.
Would it be better to handle the unwrap?

2023-12-12 22:58 UTC, merged