Links, paths, and anchors
holochain/docs-pages pull request #453
Opened 2024-06-06 22:07 UTC by pdaoust

Seeking review for:

* Succinctness of prose -- do you get lost? Is there too much information, is the complex stuff (e.g., introducing _how_ to get a hash for linking) introduced too early?
* Correctness of code at first glance -- I have to confess I haven't tried compiling any of it yet.

2024-06-07 21:10 UTC, mjbrisebois requested changes
Looks great.  I didn't know how to use the anchor functions until reading this.

2024-06-07 21:10 UTC, mjbrisebois commented on src/pages/build/links-paths-and-anchors.md
> +```
Are these supposed to have the same example code?

2024-06-07 23:25 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +* An optional **tag** that can hold a small amount of arbitrary bytes, up to 4 kb
hdk docs say the max is 1 kb (https://docs.rs/hdk/latest/hdk/link/fn.create_link.html) -- I can't actually find where this limit is applied in the codebase so not sure which is accurate

2024-06-07 23:29 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +A link is considered dead once its creation action has one or more delete-link actions associated with it.
I might also copy the same disclaimer from the entries page: "deleting" a link just creates another action marking the link as deleted and does not actually delete any data. And that a future potential purge feature will not apply to links as they are only actions.

2024-06-07 23:31 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Every link has a type that you define in an integrity zome, just like [an entry](/build/entries/#define-an-entry-type). Links are simple enough that they have no entry content. Instead, their data is
The phrasing of sentences 2-4 is a bit confusing to me. I might just say explicitly: "a link is commited to the source chain as an action with no associated entry"

2024-06-07 23:32 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Links can't be updated; they can only be created or deleted.
Should we give some clarifying rationale for why they can't be deleted?

2024-06-07 23:40 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +A link is considered dead once its creation action has one or more delete-link actions associated with it.
I'm not sure about using the term "dead" here -- in the web 2 context it usually means that a link's target is no longer hosted anywhere. I haven't seen the term used elsewhere in holochain, maybe we should just stick with "deleted"?

2024-06-07 23:41 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +To get all live _and dead_ links, along with any deletion actions, use [`hdk::prelude::get_link_details`](https://docs.rs/hdk/latest/hdk/link/fn.get_link_details.html). This function has the same opt
same note as above about the terms "dead" and "live"

2024-06-07 23:43 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +!!! info A note on the existence of data
The section title could be more descriptive. Maybe "Link Addresses May Not Have Content"?

2024-06-07 23:46 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +It's safer to share action hashes with other peers or cells in a callback called `post_commit()`. If your coordinator zome defines this callback, it'll be called after every successful function call
Yeah this confused me too. In the context of linking to/from the action within the same zome call it was created there's no issue since all the actions will either be committed to the source chain or discarded atomically

2024-06-07 23:47 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +## Getting hashes for use in linking
I wonder if it would be clearer / better mental separation to move this section onto its own page "Hashes", and then keep this page only about links / anchors / paths.

2024-06-07 23:50 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +### External reference
May be worth noting that the external hash still needs to fit in 32 bytes.

2024-06-07 23:53 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +!!! info Linking from a DNA hash is not recommended
I think the conceptual explanation of "hot spots" deserves its own section on this page, rather than hiding it in the DNA hash section. And in general I think it's okay to create links from a known base as long as there is some reasonable expected limitation to the number of links that will be created off it.

2024-06-08 00:25 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +If all you need is a count of matching links, such as for an unread messages badge, use [`hdk::prelude::count_links`](https://docs.rs/hdk/latest/hdk/prelude/fn.count_links.html). It has a different i
Might be worth noting some gotchas with count_links: it goes to the network first, so if you end up asking 2 different peers with differing dht syncs you may get 2 different answers (which may be odd behavior if your unread messages badge shows a smaller number than before without you reading any messages). You may also get a different count as the number returned from get_links for the same reason.

2024-06-08 00:39 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Sometimes the easiest way to discover a link base is to embed it into the application's code. You can create an **anchor**, an entry whose content is a well-known blob, and hash that blob any time yo
I think calling it an entry or blob that doesn't need to exist just adds confusion. An anchor as a hash that is already known to every user. One way to make it known to every user is to hard-code it. It doesn't need to be generated by hashing some human meaningful data, it could just be 32 arbitrary bytes.

2024-06-08 00:41 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +!!! info Avoiding DHT hot spots
same note as above -- I think hot spots could be expanded on in its own section

2024-06-08 00:46 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Sometimes the easiest way to discover a link base is to embed it into the application's code. You can create an **anchor**, an entry whose content is a well-known blob, and hash that blob any time yo
It's also a little confusing that we have this *concept* of an anchor, and then we also have an opinionated implementation in the HDK - might be helpful to distinguish them explicitly

2024-06-08 00:47 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +In the HDK, an 'anchor' is just a path with two levels of hierarchy. The examples below show how to implement the path-based examples above, but as anchors. Generally the implementation is simpler.
Maybe note that this is the HDK's opinionated implementation of the anchor concept.

2024-06-08 00:49 UTC, mattyg requested changes
awesome stuff thanks for taking this on!

2024-06-08 00:53 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +## Reference
There are some opinionated path libraries that maybe we should link to here:
- https://github.com/holochain-open-dev/holochain-prefix-index
- https://github.com/holochain-open-dev/holochain-time-index
- https://github.com/holochain-open-dev/ranking-index
- https://github.com/holochain-open-dev/keyword-index

2024-06-17 19:43 UTC, c12i approved these changes

2024-06-17 19:43 UTC, c12i commented on src/pages/build/entries.md
> +  director_hash: EntryHash::from_raw_36(vec![ /* hash of 'Sergio Leone' entry */ ]),
Wouldn't it be useful to also show how to get `/* hash of 'Sergio Leone' entry */`, or is this covered elsewhere in the guide?

2024-09-27 21:53 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +* An optional **tag** that can hold a small amount of arbitrary bytes, up to 4 kb
yup, you're right: https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/sys_validate.rs#L34

2024-09-27 21:55 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +Links can't be updated; they can only be created or deleted.
sure... if only I knew why 🤣

2024-09-27 21:59 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +## Getting hashes for use in linking
yup, great thing to do in a follow-up -- or put all the content on 'Working with Data'

2024-09-27 22:06 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +If all you need is a count of matching links, such as for an unread messages badge, use [`hdk::prelude::count_links`](https://docs.rs/hdk/latest/hdk/prelude/fn.count_links.html). It has a different i
Good point, although I feel like there's an entire story about that re: eventual consistency everywhere.

2024-09-27 22:32 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +If all you need is a count of matching links, such as for an unread messages badge, use [`hdk::prelude::count_links`](https://docs.rs/hdk/latest/hdk/prelude/fn.count_links.html). It has a different i
Yeah it's more than just that though since it doesn't go to your cache so you may have more links than you receive via count

2024-09-30 19:46 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +Sometimes the easiest way to discover a link base is to embed it into the application's code. You can create an **anchor**, an entry whose content is a well-known blob, and hash that blob any time yo
Thoroughly agree re: concept vs named implementation.

2024-09-30 19:48 UTC, pdaoust commented on src/pages/build/entries.md
> +  director_hash: EntryHash::from_raw_36(vec![ /* hash of 'Sergio Leone' entry */ ]),
yup, there's a section on it elsewhere, although it's a bit long-winded. I might make it into its own article.

2024-11-12 23:19 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +```
solved by deleting all mentions of `hash_path::Anchor`

2024-11-12 23:22 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +## Getting hashes for use in linking
done!

2024-11-22 19:57 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +## Reference
I skipped the last two because I don't want to point to obsolete code. But yeah, great suggestion.

2024-11-22 19:59 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +## Reference
Unfortunately I think they're all outdated -- maybe we should leave them out for now and make an issue to include when they are updated.

2024-11-22 20:42 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +A link is considered dead once its creation action has one or more delete-link actions associated with it.
I think I'll stick with 'dead' for now -- I get that it has a different meaning in Web2, but it's used in the [codebase](https://github.com/holochain/holochain/blob/develop/crates/holochain_zome_types/src/metadata.rs#L79-L80) to describe entries whose creation actions have all been marked deleted, and I want some word to suggest that it hasn't been removed -- there's still a body lying around :)

2024-11-29 20:08 UTC, mattyg commented on src/pages/build/index.md
> +* [Links, Paths, and Anchors](/build/links-paths-and-anchors/) --- creating and deleting
```suggestion
* [Links, Paths, and Anchors](/build/links-paths-and-anchors/) --- querying for data without already knowing the data's hash
```

I take these lines as being intended to be a quick description of the content of the page.

2024-11-29 20:13 UTC, mattyg commented on .cspell/words-that-should-exist.txt
> +ified
?

2024-11-29 20:18 UTC, mattyg commented on src/pages/build/identifiers.md
> +---
This page is fantastic. I love the ratio of code to prose. Amazing work

2024-11-29 20:20 UTC, mattyg commented on src/pages/build/identifiers.md
> +let director_entry_hash = EntryHash::from_raw_36(vec![/* Sergio Leone's hash */]);
maybe we should just generate the hash of the "Sergio Leone" string here too? Just one short line of code.

2024-11-29 20:27 UTC, mattyg commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
I'm not sure it would make sense to do here if this was a real app? Because I assume we'd want to display the name of the director so we'd want to store that not just its hash. 

And I don't think we necessarily need to include a code example of `from_raw_36` since we have another example with `from_raw_32` above. Was there some reason you wanted to include this instead of just the director name? Or is the idea that we should have a `Director` entry type this is referencing?

I know these are just little standalone examples but I like the idea that they form a sensible narrative of building an app as we go.

2024-11-29 20:32 UTC, mattyg commented on src/pages/build/identifiers.md
> +```
love love love these little snippets as you read through.

2024-11-29 20:37 UTC, mattyg commented on src/pages/build/identifiers.md
> +let my_current_id = agent_info()?.agent_latest_pubkey;
:grimacing: makes me want to delete `agent_latest_pubkey` from holochain until its actually used and deepkey is stable, since its effectively a placeholder right now.

I might just not mention it here :disappointed:

2024-11-29 20:39 UTC, mattyg commented on src/pages/build/identifiers.md
> +### External reference
:heart: :heart: :heart:

2024-11-29 20:40 UTC, mattyg commented on src/pages/build/identifiers.md
> +pub struct MovieLoan {
:laughing: love this example

2024-11-29 20:41 UTC, mattyg commented on src/pages/build/identifiers.md
> +  loan_terms: ActionHash,
might make this field `loan_duration` or `return_date` timestamp so we don't need a LoanTerm entry that isn't actually created in any other snippets

2024-11-29 20:43 UTC, mattyg commented on src/pages/build/identifiers.md
> +* When you write an action, you can specify "relaxed chain top ordering". We won't go into the details here, <!-- TODO: fill this in when I write about zome call lifecycles -->but when you use it, th
might be good to make a note in the github issue about chain top ordering docs (https://github.com/holochain/docs-pages/issues/496) referencing this TODO

2024-11-29 20:47 UTC, mattyg commented on src/pages/build/identifiers.md
> +* You may safely use the hash of an action you've just written as data in another action in the same function (e.g., in a link or an entry that contains the hash in a field), as long as you're not us
```suggestion
* You may safely use the hash of an action you've just written as data in another action in the same function (e.g., in a link or an entry that contains the hash in a field).
```

I don't think that's right because "relaxed" just causes the draft chain of new actions to be written on top of whatever the new chain HEAD is. It doesn't reorder the draft chain of actions. Its specifically if you make 2 simultaneous zome calls and one writes to the chain before the other has finished.

2024-11-29 20:48 UTC, mattyg commented on src/pages/build/identifiers.md
> +* Don't communicate the action hash with the front end, another cell, or another peer on the network via a remote function call or [signal](/concepts/9_signals/) _from within the same function that w
wow amazing gotcha I've never run into this and never thought of it.

2024-11-29 20:49 UTC, mattyg commented on src/pages/build/index.md
> +* [Links, Paths, and Anchors](/build/links-paths-and-anchors/) --- creating relationships between data
:heart:

2024-11-29 20:53 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Get all the _live_ (undeleted) links attached to a hash with the [`hdk::prelude::get_links`](https://docs.rs/hdk/latest/hdk/link/fn.get_links.html) function.
:+1:

2024-11-29 21:14 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Currently `count_links` retrieves all links from the remote peer, then counts them locally. We're planning on changing this behavior so it counts links on the remote peer and sends the count, to save
wow I just searched MM and found the discussion about this. I did not realize this!

2024-11-29 21:18 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +Currently `count_links` retrieves all links from the remote peer, then counts them locally. We're planning on changing this behavior so it counts links on the remote peer and sends the count, to save
```suggestion
Currently `count_links` retrieves all link hashes from the remote peer, then counts them locally. So it is less network traffic than a `get_links` request, but more network traffic than just sending an integer.
```

wow I just searched MM and found the discussion about this. I did not realize this!

Though actually I like it better than how I thought i was implemented since it does appear to merge your locally stored links with the received hashes and thus you can receive a links count integer that is less than your locally stored links. I don't know if we want to state we'll be refactoring it in this way.

2024-11-29 21:20 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +When you want to create more complex collections, you'll need to use the paths library directly.
```suggestion
When you want to create more complex collections, you'll want to use the paths library directly.
```

2024-11-29 21:23 UTC, mattyg commented on src/pages/build/working-with-data.md
> +All actions are public.
Might be worth a sentence that peers store data locally in sqlite database with encryption enabled by default, but this can be disabled by compiling holochain without `sqlite_encrypted` (or maybe that's overkill and ignore me)

2024-11-29 21:26 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +A link is considered dead once its creation action has one or more delete-link actions associated with it.
love the clarification around dead/deleted you added.

2024-11-29 21:27 UTC, mattyg commented on src/pages/build/entries.md
> +  director_hash: EntryHash::from_raw_36(vec![ /* hash of 'Sergio Leone' entry */ ]),
I think this is resolved by the content addressing page

2024-12-03 18:26 UTC, pdaoust commented on .cspell/words-that-should-exist.txt
> +ified
as in "JSON-ified" 🤷🏼‍♂️

2024-12-03 18:28 UTC, pdaoust commented on src/pages/build/identifiers.md
> +An agent can get their own ID by calling [`hdk::prelude::agent_info`](https://docs.rs/hdk/latest/hdk/info/fn.agent_info.html). Note that agents may change their ID if their public key has been lost o
that wasn't lost on me either :) I just wanted to give some rationale for why there's something called `agent_latest_pubkey`, which prompts the question "what else might it have been, and why?"

I'd rather not get this deep into the weeds, but the HDK kinda pushes me there.

2024-12-03 18:29 UTC, pdaoust commented on src/pages/build/identifiers.md
> +  loan_terms: ActionHash,
okay, that's fine -- I wanted to show a struct that had a mixture of different kinds of hashes, but `EntryHash` and `AgentPubKey` is prob enough.

2024-12-16 23:03 UTC, pdaoust commented on src/pages/build/identifiers.md
> +* When you write an action, you can specify "relaxed chain top ordering". We won't go into the details here, <!-- TODO: fill this in when I write about zome call lifecycles -->but when you use it, th
done

2024-12-16 23:06 UTC, pdaoust commented on src/pages/build/identifiers.md
> +* You may safely use the hash of an action you've just written as data in another action in the same function (e.g., in a link or an entry that contains the hash in a field), as long as you're not us
it doesn't reorder things _within_ the atomic block of actions, no, but their action hashes will all be different from what the function call thought they were, if the block gets rebased on a new chain head after the function completes.

2024-12-16 23:07 UTC, pdaoust commented on src/pages/build/identifiers.md
> +* Don't communicate the action hash with the front end, another cell, or another peer on the network via a remote function call or [signal](/concepts/9_signals/) _from within the same function that w
super handy function -- scaffolded zomes use this trick as a way of updating front-end state on self-authored data.

2024-12-16 23:08 UTC, pdaoust commented on src/pages/build/links-paths-and-anchors.md
> +Currently `count_links` retrieves all links from the remote peer, then counts them locally. We're planning on changing this behavior so it counts links on the remote peer and sends the count, to save
I learned something new too! didn't realise it was just the link _hashes_; that's a little better. I guess getting a remote count would potentially be less accurate, but if all I want is an unread badge or something like that, I'll take performance over precision (which is never guaranteed anyway).

2024-12-16 23:12 UTC, pdaoust commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
hmmmm, valid point. We use `director_entry_hash` a couple times before this in the document to show how to retrieve links from a base. So yes, I guess that would necessitate a `Director` entry. Understand about the noise, but explaining `get_links` kinda forced me to create the noise already :)

2024-12-16 23:20 UTC, pdaoust commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
hm, looks like I'm borrowing from the work on Entries, where that was part of the struct -- but no `Director` entry was ever defined!

2024-12-16 23:20 UTC, mattyg commented on src/pages/build/identifiers.md
> +* You may safely use the hash of an action you've just written as data in another action in the same function (e.g., in a link or an entry that contains the hash in a field), as long as you're not us
Oh huh. I think I see what you're saying. Because the rebase isn't re-running the zome call, its just changing the *actual* action hash of the CreateEntry, and not the reference to it in the CreateLink. 

Oy I don't like that this is exposed to app devs. Good to include in the docs though.

2024-12-16 23:26 UTC, pdaoust commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
turns out my links page leans heavily on the existence of a `Director` entry type, so I created a simple `Director(pub string)` entry type. A little bit of noise on the entries page, but it's needed anyway.

2024-12-16 23:27 UTC, mattyg commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
I don't think so, in the Entries page `director` is just a string with the director's name.

2024-12-19 16:55 UTC, pdaoust commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
don't think so == don't think it's needed or don't think it's noisy?

2024-12-20 00:56 UTC, mattyg commented on src/pages/build/identifiers.md
> +  director_entry_hash: director_entry_hash,
Oh, sorry that was a response to your first comment -- the second hadn't loaded for me yet. Your change looks good!

2024-12-20 22:17 UTC, pdaoust commented
@mattyg thanks so much for all the encouragement -- glad to hear it's landing 🙏🏼 And I think I'm getting the hang of writing Rust code (and hApp code), although there are some gnarly things along the way (e.g., holochain/holochain#4575 ).

I've tried compiling all the code samples and discovered that there were a fair few errors; would you be willing to re-review this PR and make sure my 'solutions' to the errors are all reasonably idiomatic?

2024-12-20 22:27 UTC, mattyg commented on src/pages/build/entries.md
> +  release_date: Timestamp(-95_472_000_000_000), // 1966-12-23
I'd prefer to construct the timestamp from a human readable date. It looks like we can do so via `chrono::DateTime<Utc>` https://docs.rs/hdk/latest/hdk/prelude/struct.Timestamp.html#impl-From%3C%26DateTime%3CUtc%3E%3E-for-Timestamp

2024-12-20 22:28 UTC, mattyg commented on src/pages/build/entries.md
> +  release_date: Timestamp(-95_472_000_000_000),
Same comment as above about constructing the timestamp

2024-12-20 22:31 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +    GetLinksBuilder::try_new(path_to_movies_starting_with_g.path_entry_hash()?, LinkTypes::MovieByFirstLetter)?
```suggestion
    GetLinksInputBuilder::try_new(path_to_movies_starting_with_g.path_entry_hash()?, LinkTypes::MovieByFirstLetter)?
```

2024-12-20 22:32 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +        ..tag_prefix("year:196".as_bytes().to_owned().into())
```suggestion
        .tag_prefix("year:196".as_bytes().to_owned().into())
```

2024-12-20 23:23 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +let links_to_movies_starting_with_g = get_links(
```suggestion

```

2024-12-20 23:23 UTC, mattyg commented on src/pages/build/links-paths-and-anchors.md
> +)?;
```suggestion
```

2024-12-20 23:57 UTC, mattyg requested changes
couple issues in comments, otherwise looks good.

2025-01-02 19:56 UTC, pdaoust commented on src/pages/build/working-with-data.md
> +All actions are public.
I'll put a small note about it being encrypted.

2025-01-03 03:23 UTC, mattyg approved these changes
:fire: :fire:

2025-01-08 21:46 UTC, merged