Update docs for Holochain 0.3
holochain/docs-pages pull request #462
Opened 2024-07-24 22:01 UTC by pdaoust

* Update scaffolding flow and output samples
* Update code samples
* Change language that talks about Launcher using Tauri
* A few prose reorganisations to make it flow better with the new scaffolding flow
* Language tweaks, esp around `hc spin` and `hc launch`
* Fix broken link
* Add mention of p2p Shipyard

2024-07-25 00:03 UTC, ThetaSinner approved these changes
Looks great! A few minor comments which may or may not be useful :)

2024-07-25 00:03 UTC, ThetaSinner commented on src/pages/get-started/3-forum-app-tutorial.md
> +Holochain development shell spawned. Type exit to leave.
Maybe good to demonstrate at this point that `holochain` or `hc` is present? Something like `hc --version`? Or maybe that's overkill :D

2024-07-25 00:03 UTC, ThetaSinner commented on src/pages/get-started/3-forum-app-tutorial.md
> +A quick note: if while scaffolding some part of your hApp, you realize you've made a mistake (a typo or wrong selection for instance), as long as you haven't finished scaffolding that portion, **you
Nice, this is a question that comes up relatively often when I show people scaffolding :)

2024-07-25 08:34 UTC, matthme commented on src/pages/get-started/3-forum-app-tutorial.md
> +Holochain development shell spawned. Type exit to leave.
I think that's a good idea. It's a nice way of showing what entering nix shell actually did for you. Because any use of these binaries otherwise happens under the hood, via npm scripts that invoke `hc` which then invokes `holochain` through `hc sandbox` or a subcommand like `hc launch` and so you wouldn't really notice.

2024-07-25 08:36 UTC, matthme commented on src/pages/get-started/3-forum-app-tutorial.md
> +A quick note: if while scaffolding some part of your hApp, you realize you've made a mistake (a typo or wrong selection for instance), as long as you haven't finished scaffolding that portion, **you
In the same vein, I started the habit of commiting my changes after each scaffolding step such that I can revert an erroneous step instead of having to start all over. I'm wondering whether that's something we should recommend as well as long as there is no built-in way to revert scaffolding steps.

2024-07-25 08:41 UTC, matthme approved these changes
Looks good to me too :+1:

2024-07-25 09:10 UTC, c12i commented on src/pages/get-started/3-forum-app-tutorial.md
> +Inside of your `dnas/` folder, the scaffolding tool generated a `forum/` folder and, inside of that, the folders and files that the DNA needs. At this point you have a skeleton structure for your `fo
The instructions are printed out a little further after scaffolding a zome pair

2024-07-25 09:36 UTC, c12i requested changes

2024-07-25 09:36 UTC, c12i commented on src/pages/get-started/3-forum-app-tutorial.md
> +A quick note: if while scaffolding some part of your hApp, you realize you've made a mistake (a typo or wrong selection for instance), as long as you haven't finished scaffolding that portion, **you
I encountered this issue myself and have been experimenting with a feature that allows scaffolding from a config file. As part of my work on a replay functionality, developers will be able to define a YAML (tentative) file like the example below. While this won't revert previously made changes, it will facilitate planning your scaffold before feeding it to the cli.

```yaml
web-app:
  name: "my-app"
  description: "my description"
  holo: true
  disable-fast-track: false
  setup-nix: true
  package-manager: npm | pnpm | yarn | bun

dna:
  app: "my_app"
  name: "my_dna"

zome:
  coordinator: <path>
  integrity: <path>
  dna: "my_app"
  name: "my_zome"

entry-type:
  crud: "crud"
  # updatable: true
  # deletable: true
  fields:
    - name: "name"
      type: "String"
      widget: "TextField"
      linked_from:
  link-from-original-to-each-update: true
  reference-entry-hash: false
  zome: "my_zome"
  no-ui: false

link-type:
  from-referenceable: "EntryA"
  to-referenceable: "EntryB"
  zome: "my_zome"
  dna: "my_dna"
  bidirectional: true
  delete: true
  no-ui: false
```

I realize this might be more appropriate for the scaffolding repo, but I wanted to share it here since I was brainstorming this idea just yesterday.

2024-07-25 09:36 UTC, c12i commented on src/pages/get-started/3-forum-app-tutorial.md
> +script lang="ts">
```suggestion
<script lang="ts">
```

2024-07-25 09:36 UTC, c12i commented on src/pages/get-started/3-forum-app-tutorial.md
> +❯ svelte
I second this, mostly because of the fact that we are also transitioning to a new styling system, which is already reflected in the `react` template

2024-07-25 09:36 UTC, c12i commented on src/pages/get-started/3-forum-app-tutorial.md
> +You can get help on every one of these subcommands and its parameters by typing `hc scaffold <subcommand> --help`.
I think this would be a good place to also add a link to the the cli reference. Would ideally prefer a docs.rs link for the 0.3 specific version but the crate currently fails to build due to docs.rs limitations [here](https://docs.rs/crate/holochain_scaffolding_cli/0.3000.2/builds), opened an [issue](https://github.com/rust-lang/docs.rs/issues/2566) on docs.rs to have this addressed though. For now we can settle for a [link to the markdown file](https://github.com/holochain/scaffolding/blob/develop/guides/cli.md), what do you think?

2024-07-25 19:01 UTC, jost-s approved these changes

2024-07-25 19:01 UTC, jost-s commented on src/pages/get-started/4-packaging-and-distribution.md
> +The steps for publishing an app to the Launcher's app store are documented in the Github repository of the Holochain Launcher [here](https://github.com/holochain/launcher#publish-an-app-to-launchers-
```suggestion
The steps for publishing an app to the Launcher's app store are documented in the [Github repository of the Holochain Launcher](https://github.com/holochain/launcher#publish-an-app-to-launchers-app-store).
```

2024-07-26 12:47 UTC, c12i approved these changes

2024-07-29 18:00 UTC, pdaoust commented on src/pages/get-started/3-forum-app-tutorial.md
> -tocData:
TOCs are now autogenerated, and leaving it up to a manually generated TOC is brittle.

2024-07-29 20:50 UTC, pdaoust commented on src/pages/get-started/3-forum-app-tutorial.md
> +You'll notice that we used the word "action" a lot. In fact, **we call the a source chain record an action**. In Holochain applications, data is always "spoken into being" by an agent (a participant)
good advice.

2024-07-29 20:59 UTC, merged