Holochain 0.4 upgrade guide
holochain/docs-pages pull request #499
Opened 2024-11-22 18:04 UTC by pdaoust

Incorporates all the breaking changes in 0.4 and peripheral tooling.

2024-12-09 23:43 UTC, pdaoust reviewed
don't deploy until 0.4 is live and recommended.

2024-12-09 23:43 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +---
The URLs in this document need to be updated once the Rustdoc is published to docs.rs

2024-12-10 11:25 UTC, matthme commented on src/pages/get-started/install-advanced.md
>  nix develop --override-input holochain "github:holochain/holochain?ref=main-0.4" github:holochain/holonix
I just tried this command like so and it seemed to work as well:
```
nix develop github:/holochain/holonix?ref=main-0.4
```
If someone can verify this I think this would be much cleaner.

2024-12-10 11:25 UTC, matthme commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +* The `InstallApp` admin API endpoint has had its request payload changed.
I wonder whether it would be worth mentioning here that the dna properties can now be provided at install time [see changelog](https://github.com/holochain/holochain/blob/main-0.4/CHANGELOG.md#20241125215336). Or mention that further down where it's currently only mentioned that the agent key is now optional in the install app payload.

2024-12-10 16:19 UTC, ThetaSinner commented on src/pages/get-started/install-advanced.md
>  nix develop --override-input holochain "github:holochain/holochain?ref=main-0.4" github:holochain/holonix
What's here is actually wrong and is likely to break. That's asking for the latest version of Holonix, which could be supporting any Holochain version and then injecting some version of Holochain into it, without matching the Lair version or anything like that.

I'm assuming we hadn't created the `main-0.4` branch when this was written. 

It is valid to do version overrides, just not like this. For example, the following one-liner would downgrade you to Holochain `0.4.0-rc.1`

```suggestion
nix develop --override-input holochain "github:holochain/holochain?ref=holochain-0.4.0-rc.1"  "github:/holochain/holonix?ref=main-0.4"
```

However, it gives you `lair-keystore` at 0.5.3 where Holochain `0.4.0-rc.1` required `lair-keystore` at 0.5.2... So this is really opening a can of worms. Same is true for `hc-launch` and `hc-scaffold`, yes they will be provided to you, but if you mismatch the versions that Holonix is giving you then compatibility becomes your problem.

2024-12-10 16:26 UTC, ThetaSinner commented on src/pages/get-started/install-advanced.md
> +If you want to enable or disable certain Holochain features, such as unstable features, it's best to do this in a local flake file. [Read the 'Customized Holochain build'](https://github.com/holochai
That's only part of the problem. It also means that if you're using the GitHub Actions workflow provided by scaffolding which does `nix develop` then your CI will be slow because it will build Holochain every time.

2024-12-10 17:10 UTC, mattyg commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +    "variant1": null
```suggestion
    "MyEnumType": {"Variant1": null}
```

2024-12-10 17:10 UTC, mattyg commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +"variant1"
```suggestion
    "MyEnumType": "Variant1"
```

2024-12-10 17:20 UTC, zippy approved these changes
This looks great apart from suggestions others have left.

2024-12-10 18:58 UTC, ThetaSinner requested changes
I wouldn't know how to upgrade my Holonix, or NPM and Rust dependencies based on this guide. I'd also like some more details on Rust code changes required please.

2024-12-12 21:18 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +* The `InstallApp` admin API endpoint has had its request payload changed.
I'm not too worried about non-breaking changes -- unless this *is* a breaking change that didn't get put into the changelog?

2024-12-12 21:20 UTC, pdaoust commented on src/pages/get-started/install-advanced.md
> +If you want to enable or disable certain Holochain features, such as unstable features, it's best to do this in a local flake file. [Read the 'Customized Holochain build'](https://github.com/holochai
```suggestion
If you want to enable or disable certain Holochain features, such as unstable features, it's best to do this in a local flake file. [Read the 'Customized Holochain build'](https://github.com/holochain/holonix?tab=readme-ov-file#customized-holochain-build) on the Holonix readme to find out how. Keep in mind that, because you'll be creating a custom Holochain binary, you won't be able to take advantage of the package cache, so it'll take a while to compile Holochain on your machine or run CI tasks with it.
```

2024-12-12 21:21 UTC, pdaoust commented
> I wouldn't know how to upgrade my Holonix, or NPM and Rust dependencies based on this guide. I'd also like some more details on Rust code changes required please.

@ThetaSinner I've rewritten the guide; is this more what you're thinking now?

2024-12-12 21:38 UTC, jost-s commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +The default serialization for bare (no-data) enum variants has changed. Previously, they would look like this (JSON representation):
```suggestion
The default serialization for unit-like enum variants has changed. Previously, they would look like this (JSON representation):
```

2024-12-12 21:43 UTC, jost-s commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +Then navigate to the `tests/` folder and run your package manager's update command like you did at the project's top level in the last step.
`npm update` should only be run from the project's root folder.

2024-12-12 21:44 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +Then navigate to the `tests/` folder and run your package manager's update command like you did at the project's top level in the last step.
awesome, I wasn't sure about that

2024-12-12 21:44 UTC, jost-s commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +Then run navigate to the `ui/` folder and run your package manager's update command.
You can update all dependencies in root, test and ui folders and then run `npm i` just once.

2024-12-12 21:45 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> ++hdi = "=0.5.0-rc.1"
These all need to be fixed once a release is cut. There are many of these.

2024-12-12 21:48 UTC, jost-s commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +The biggest change for 0.4 is that some unstable features aren't compiled into official Holochain releases by default. We're doing this to focus on a stable core Holochain with the minimal feature se
```suggestion
The biggest change for 0.4 is that some features are marked `unstable` and arent' compiled into Holochain by default. We're doing this to focus on a stable core Holochain with the minimal feature set that most projects need. The removed features are still available as Rust feature flags, so you can compile a custom Holochain binary if you need them. Here's the full list, along with their feature flags:
```

2024-12-12 21:50 UTC, jost-s commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +`unstable-functions` is a flag used by both the Holochain conductor _and_ the [`hdi`](https://docs.rs/hdi/latest/hdi) and [`hdk`](https://docs.rs/hdk/latest/hdk) crates, and some of the functions als
I think that's an implementation detail that app devs don't need to know about.
```suggestion
Some of the unstable functions need other Holochain features enabled (e.g., `is_same_agent` requires a conductor with `unstable-dpki` enabled; see the list above).
```

2024-12-12 22:13 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +`unstable-functions` is a flag used by both the Holochain conductor _and_ the [`hdi`](https://docs.rs/hdi/latest/hdi) and [`hdk`](https://docs.rs/hdk/latest/hdk) crates, and some of the functions als
It seems like those few people who need to know about this will need to know that they have to turn on `unstable-functions` in both the zomes and the custom holochain binary they build, along with the feature they depend on, in order for unstable functions to be plumbed all the way through. Is that not true?

2024-12-12 22:19 UTC, jost-s commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +`unstable-functions` is a flag used by both the Holochain conductor _and_ the [`hdi`](https://docs.rs/hdi/latest/hdi) and [`hdk`](https://docs.rs/hdk/latest/hdk) crates, and some of the functions als
Okay yes, then I'd be explicit about it and say "`unstable-functions` has to be enabled both when building the Holochain binary **and** in the Cargo.toml of zomes using `hdi` and `hdk`.

2024-12-12 22:31 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +`unstable-functions` is a flag used by both the Holochain conductor _and_ the [`hdi`](https://docs.rs/hdi/latest/hdi) and [`hdk`](https://docs.rs/hdk/latest/hdk) crates, and some of the functions als
oh -- I tried to say that :) I'll go back and see how I can be more explicit.

2024-12-13 11:38 UTC, ThetaSinner commented on src/pages/get-started/install-advanced.md
> +If you want to enable or disable certain Holochain features, such as unstable features, it's best to do this in a local flake file. [Read the 'Customized Holochain build'](https://github.com/holochai
"to compile Holochain on your machine. The same will be true on CI, where you should consider setting up your own caching"

Something like that?

2024-12-13 12:12 UTC, ThetaSinner reviewed
Pausing again because I got stuck

An app scaffolded at 0.3 doesn't `npm start` because the UI is broken

```
[0]     48 |     await this.fetchWorzle();
[0]     49 |     toRaw(this.client).on("signal", signal => {
[0]   > 50 |       if (signal.zome_name !== "ohfour") return;
[0]        |                  ^^^^^^^^^
[0]     51 |       const payload = signal.payload as OhfourSignal;
[0]     52 |       if (payload.type !== "EntryCreated") return;
[0]     53 |       if (payload.app_entry.type !== "Worzle") return;
```

I'm using Vue but I'm pretty sure this issue should show up for an app scaffolded with any UI framework.

2024-12-13 12:12 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +### JavaScript tooling
Confusing title, tryorama is also javascript tooling. Maybe something like "Node dependencies in the project root`?

2024-12-13 12:12 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +### Tryorama tests
Inaccurate, we're updating tryorama, not the tests. Maybe `Node dependencies for the test workspace`?

2024-12-13 12:12 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +yarn upgrade
I'd also move this to the end of the section because we may as well update all our dependencies at once once we're done editing `package.json` files. It can all be done in one command.

2024-12-13 12:12 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> ++holochain = { version = "0.4.0-rc.2", features = ["unstable-countersigning", "unstable-functions"] }
Nobody is using countersigning. It's so complex that I don't believe anybody has figured out how to use it and put it in their app without talking to us. It took me weeks, full time, trying to figure out how to get it behaving properly and then it was packed full of bugs. The chances that anybody else has bothered going through that is low.

Anybody building Holochain into the project to make their own runtime, should know how to use Rust features. I'd just drop this section. The section above that describes how you need to build Holochain with feature flags and also the HDK/HDI should be sufficient I believe.

2024-12-13 12:12 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> ++holochain = { version = "0.4.0-rc.2", features = ["unstable-countersigning", "unstable-functions"] }
Part of the reason for disabling this stuff is that most people aren't using what we're putting behind feature flags. We wanted to let people use it if they wanted to, but the main reason for using Rust features really was to be able to keep testing that code until we can get to it and make it work properly.

2024-12-13 16:30 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> ++hdi = "=0.5.0-rc.1"
Would it work to just change it to e.g. `hdi = "^0.4.6"`?

2024-12-13 16:49 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> ++holochain = { version = "0.4.0-rc.2", features = ["unstable-countersigning", "unstable-functions"] }
I do know of one project in the wild that's using countersigning, but point taken -- those who need the features will probably have the chops to do what I'm describing.

2024-12-13 17:21 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +     "@holochain-playground/cli": "^0.300.1",
Playground 0.300 seems to work fine with hApps built for 0.4 🤷🏼‍♂️

2024-12-13 17:58 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +### JavaScript client now receives system signals
@ThetaSinner I've added a bit of JS to update client/Tryorama code for the breaking change in the signal handler. Does this look good?

2024-12-13 21:57 UTC, pdaoust commented on src/pages/get-started/install-advanced.md
>  nix develop --override-input holochain "github:holochain/holochain?ref=main-0.4" github:holochain/holonix
wait! I just discovered this is already fixed in `main`. Guess I just didn't sync this branch with `main` lately.

2024-12-16 21:14 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +### JavaScript client now receives system signals
@ThetaSinner I'd like to see the code that's not building for you -- it's working for me. Looks like you're trying to read `SignalType.AppSignal` rather than `SignalType.App`?

2024-12-16 21:47 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +    nix develop
hm, a bug in my shell styling. Should be a one-liner for easy copy/pasting anyway.

2024-12-16 22:54 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +```diff:rust
Code compiles, functions not tested.

2024-12-16 22:55 UTC, pdaoust commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +```diff:typescript
`tsc` can compile this too -- again not tested.

2024-12-20 14:33 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +* **[DHT sharding](/concepts/4_dht/) `unstable-sharding`**: Lessens the load of each peer in large network, allowing them to take responsibility for validating and storing only a subset of a DHT's en
This feature flag doesn't remove code, it just forces configuration. By default in 0.4 you must set the network tuning parameter `gossip_arc_clamping` in your conductor config to "empty" or "full". The default is "full" and anything else will produce an error. If you enable the feature then you can still set "empty" or "full" but an extra option is available, "none". Where "none" is the default and let's Kitsune manage arc sizing.

2024-12-20 14:34 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +* **[Warrants](/concepts/7_validation#remembering-validation-results) `unstable-warrants`**: Spreads news of validation failure around the network, allowing peers to recognize bad actors and take act
This feature is new and we know there are bugs, use with caution

2024-12-20 14:36 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +* **Chain head coordination `chc`**: Developed for Holo, allows source chain changes to be copied from one device to another without causing chain forks. (This pre-existing feature flag is no longer
Technically it allows you to back up your source chain writes to a remote server that implements the CHC protocol over HTTP. Then you can restore your source chain from that backup. Being able to move machines is a side-effect of what the feature does.

2024-12-20 14:37 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +    * Related to DPKI (enable `unstable-dpki` if you want to use these, which are both new to 0.4):
Both? Is there a function missing here then? Should this also list `is_same_agent`?

2024-12-20 14:48 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +```diff:typescript
This is just a matter of running the app and seeing whether created entries show up immediately on the UI or whether you have to reload the page. If they show up right away, this is working

2024-12-20 14:50 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +For JavaScript front ends and Tryorama tests, the signal handler callback for `AppWebsocket.prototype.on("signal", cb)` should now take a [`Signal`](https://github.com/holochain/holochain-client-js/b
Can note here that system signals are currently only used for countersigning, which is disabled. So you can filter out system signals for now.

We are planning to use these for other things so it's probably worth making it clear that this is explicitly filtering them out.

2024-12-20 14:51 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +This change is only relevant if you're building a runtime that can install hApp bundles.
If you're doing that, you might just as well be using Holochain as a library and need a whole other list of changes. I'd just say "using the Rust client to install apps on Holochain" or something like that here

2024-12-20 14:54 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +It's unknown exactly what might happen if nodes with DHT sharding disabled try to gossip in the same network as nodes without DHT sharding. Presumably this is still possible, but it might cause unexp
No, that is known. Because we've run with `gossip_arc_clamping = "full"` in the same network are peers with dynamic arcs before. It will work fine but the peers who have chosen to enable `unstable-sharding` and left their `gossip_arc_clamping = "none"` might run into bugs with arc sizing. That's the reason we disabled it and until we integrate Kitsune2 and re-enable sharding, we're not going to provide support for people who run into bugs with this. At least not beyond helping diagnose that this was indeed the issue.

2024-12-20 14:58 UTC, ThetaSinner commented on src/pages/resources/upgrade/upgrade-holochain-0.4.md
> +Previous conductor and keystore SQLite databases used a hardcoded encryption key; v0.4 now uses a dynamic key. Additionally, the database paths have changed. These two things mean you won't be able t
There is an automatic migration of paths. If databases are detected at the old paths then Holochain will move them. We didn't provide a "re-encrypt" migration from the hard-coded key to dynamic keys though. It can be done, it's not impossible but we didn't think the value was high enough to justify the time.

So I'd word this to say that it's the encryption that prevents data being imported and if people want to keep their data they either need to export it through their app's UI and re-import on 0.4 or they need to provide their users with tooling to migrate the encryption keys.

Maybe that's a bit too much detail really, but conductor migration is something I'd like us to be getting better at over time :)

2024-12-20 16:36 UTC, merged